config/routes.rb
require 'resque/server'
require 'resque/scheduler'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Resque::Server.new, at: "/resque"
  devise_for :users
  root to: 'home#index'
  resources :sites, only: [:show, :new, :create, :destroy, :index]
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :sites, dependent: :destroy
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/container_server.rb
class ContainerServer < ApplicationRecord
end

app/models/db_server.rb
class DbServer < ApplicationRecord
end

app/models/file_server.rb
class FileServer < ApplicationRecord
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :account, optional: true
  validates :wp_version, presence: true
  validates :php_version, presence: true

  VALID_WP_VERSIONS = ['latest', '5.6.8']
  VALID_PHP_VERSIONS = ['7.4', '8.1']
  
  def self.create_site(current_user, ip, wp_version, php_version)
    if current_user
      ip = ''
    end
    db_hex = SecureRandom.hex(8)
    site = Site.new(
      php_version: php_version,
      wp_version: wp_version,
      admin_username: 'admin',
      admin_password: SecureRandom.hex(8),
      account_id: find_account(current_user),
      category: find_category(current_user),
      name: site_name,
      db_username: 'wp_db_' + db_hex,
      db_password: 'wp_db_pass' + db_hex,
      client_ip: ip)  
    site.save
    Server_job.perform(site.id)
    site
  end

  def self.site_name
    return LiterateRandomizer.word.downcase.delete('-') + rand(1000).to_s
  end

  def self.find_account(current_user)
    if current_user
      account = Account.find_by user_id: current_user.id
      account_id = account.id
    else
      return nil
    end
    return account_id
  end

  def self.find_category(current_user)
   return 'permanent' if current_user != nil
   return 'temporary'
  end

  def self.delete(site)
    response = RestClient::Request.execute(method: :delete, url: 'http://206.189.138.203:47157',payload: site.to_json,
                                           headers: {"Content-Type" => "application/json"})
    return response.code
  rescue Errno::ECONNREFUSED
    return 500
  rescue RestClient::ExceptionWithResponse => e
   return e.response.code
  rescue Net::HTTPBadResponse => e
    return 200
  end




end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_account

  has_one :account, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  private
  def create_account
    Account.create(user_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @sites = Site.all
    @site = Site.new
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  skip_before_action :verify_authenticity_token

  @limit = false
  def index
    @sites = Site.all
  end

  def create
    if !current_user and !verify_recaptcha
      redirect_to root_url, notice: "ReCAPTCHA verification failed!"
      return
    end
    begin
      ip = client_ip()
      if limit_reached(current_user, ip, )
        #redirect_to root_url, notice: "limit_reached"
        redirect_to root_path(:error => "limit_reached"), :method => 'post'
        return
      end
      @site = Site.create_site(current_user, ip, params[:site]['wp_version'], params[:site]['php_version'])
      @site.reload

      if @site.status == "deleted"
        redirect_to root_path(:error => "site_not_created"), :method => 'post'
      else
        redirect_to @site
      end

    rescue
      redirect_to root_path
    end

  end

  def show
    @site = Site.find(params[:id])
  end

  def destroy
    @site = Site.find(params[:id])
    response = Site.delete(@site)
    if response == 200
      @site.destroy
      #redirect_to root_path(:delete => "true"), :method => 'post'
      redirect_to root_url, notice: "Successfully Deleted!"
    else
      redirect_to root_url, notice: "Error while deleting site. Try again later."
    end
  end

  private def client_ip
    return request.remote_ip
  end

  private def limit_reached(current_user, ip)
    if not current_user and Site.where(:client_ip => ip, :status => "running").length() >= 2
      return true
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/home/index.html.erb
<style>
body{
  background-color: #f5f5f5;
  font-size: 30px;
}

h2{color: #563d7c;
  font-family: Helvetica, sans-serif;
  font-size: 60px;
  text-align: center;
}

.centre{margin-left: auto;
  margin-right: auto;
}

#logged_in_as{
  font-size: 1.5rem;
  color: white;
  }
#create_web_button{
  border-radius: 10px;
  border-style: solid;
  padding: 15px;
  background: white;
  color: black;
  text-transform: none;
  padding-top: 20px;
  font-size: 1.5rem;
}

#create_web_button:hover{
  background: #212529;
  color: white;
  }

#top_bar{
  font-size:1.5rem;
  color:black;
  width:100%;
  height:60px;
  background-color:#343a40;
}

.top-nav-left{
  float: left;
color: #f8f9fa;
font-size: 1.5rem;
height:60px;
margin-top:15px;
padding-left:10px;
}

.top-nav-right{
  float: right;
color: #c1c1c1;
height:60px;
margin-top:20px;
font-size: 1rem;
padding-left:10px;
padding-right:10px;
}

.top-nav-right a{
  text-decoration:none;
  color:white;
}

.top-nav-right a:visited{
  text-decoration:none;
  color:white;
}

.top-nav-right a:active{
  text-decoration:none;
  color:white;
}

.table-css{
  background-color:#e9ecef;
  border-color:#212529;
  border-style:solid;
  width:90%;
  font-size:1.5rem;
  -webkit-box-shadow: 20px 20px 28px -17px rgba(0,0,0,0.32);
  -moz-box-shadow: 20px 20px 28px -17px rgba(0,0,0,0.32);
  box-shadow: 20px 20px 28px -17px rgba(0,0,0,0.32);
}
tr:nth-child(even) {
          background-color: #f5f5f5;}

@keyframes fuck_taste_wp{
  0%{
    color: red;
  }
  33%{
    color: green;
  }
  66%{
    color: blue;
  }
  100%{
    color: orange;
  }
}

#fuck_twp{
  animation: fuck_taste_wp 2s ease forwards infinite;
  font-size: 1rem;
  }
</style>

<!-- Top Nav Bar -->
<div id="top_bar">
  <div class="top-nav-left"> <strong> BlogVault </strong></div>
  <% if current_user %>
    <div class="top-nav-right"> <%= link_to "Home", root_path %> | <b><%= current_user.email %> </b> | <%= link_to "Log Out", destroy_user_session_path, method: :delete %></div>
  <% else %>
    <div class="top-nav-right"> <%= link_to "Home", root_path %> | <%= link_to "Sign Up", new_user_registration_path %> | <%= link_to "Log In", new_user_session_path %></div>
  <%end%>
</div>

<center>
  <h2> Get Wordpress sites with just a click!</h2>

  <% if params[:error] == 'site_not_created' %>
    <h3 style="font-size:1.5rem;"> Error while creating site. Try again later </h3>
  <% end %>
<% if current_user %>
<h2 style="font-size: 30px;">Your Sites List </h2>
<div>
  <table class="table-css" >
    <tr style="background-color:#212529;color:#f5f5f5;">
      <th> Name </th>
      <th> Created at </th>
      <th> PHP version </th>
      <th> wordpress version </th>
      <th> url </th>
      <th> action </th>
    </tr>
  <% present = false %>
  <% @sites.each do |site| %>
    <% if site.status == "running" and site.account_id == current_user.id %>
      <% present = true %>
      <tr>
        <td> <%= link_to site.name, site %> </td>
        <td> <%= site.created_at %> </td>
        <td><%= site.php_version %></td>
        <td><%= site.wp_version %></td>
        <td> <a href = "<%= 'http://206.189.138.203/' + site.name %>" target="_blank" >http://206.189.138.203/<%= site.name %></a>  </td>
        <td><%= link_to "Delete", site_path(site),
                        method: :delete,
                        data: { confirm: "Are you sure?" } %>
                        </td>
      </tr>
    <% end %>
  <% end %>
  <% if !present%>
  <tr>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <% end %>
  </table>
</div>
<% end %>

<% if notice == "Successfully Deleted!" %>
  <h3 style="font-size:1.5rem"> <%= notice %> </h3>
<% end %>

<% if notice == "Error while deleting site. Try again later." %>
  <h3 style="font-size:1.5rem"> <%= notice %> </h3>
<% end %>

<%= form_with model: @site do |form| %>
  <div>
    <%= form.label :wp_version, "Wordpress Version" %>
    <%= form.select :wp_version, ['latest', '5.6.8'] %>
  </div>

  <div>
    <%= form.label :php_version, "PHP Version" %>
    <%= form.select :php_version, ['7.4', '8.1'] %>
  </div>
  <br>
  <div>
    <%= form.submit id: 'create_web_button'%>
  </div>
  <% if !current_user %>
    <br>
    <div>
      <% if notice %>
        <p> <%= notice %> </p>
      <% end %>
      <%= recaptcha_tags %>
    </div>
  <%end%>
<% end %>



<% if params[:error] == "limit_reached" %>
  <br><br><br><br><br><br><br>
  <h3 style="font-size:1.5rem"> You Can't create more than two sites without signing in. <%= link_to "sign up", new_user_registration_path %> </h3>
<% end %>
</center>
<br><br>
<marquee id="fuck_twp" direction="right" scrollamount="10">
Better than Tastewp.com :)
</marquee>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WpSandbox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sites/index.html.erb
<style>
body {
  background-color: powderblue;
  text-align: center;}
h1{color: blue;
  font-family: Helvetica, sans-serif;
  font-size: 60px;
  text-align: center;}
</style>


<h1> Your Sites </h1>


<% @sites.each do |site| %>
  <% unless site.account_id != current_user.id %>
  <ul>
    <%= link_to site.name, site %>
  </ul>
  <% end %>
<% end %>

<h2> <%= link_to "Home", root_url %> </h2>

app/views/sites/show.html.erb
<!-- <style>
body {
  background-color: powderblue;
  text-align: center;
  font-size: 30px;}
h1{color: blue;
  font-size: 60px;
  text-align: center;
  font-family: Helvetica}
</style> -->


<style>
body{
  background-color: #f5f5f5;
  text-align: left  ;
  font-size: 30px;}
h1{color: black;
  font-family: Helvetica, sans-serif;
  font-size: 60px;
  text-align: center;}

.centre{margin-left: auto;
  margin-right: auto;}

#logged_in_as{
  font-size: 1.5rem;
  color: white;
  }

#top_bar{
  font-size:1.5rem;
  color:black;
  width:100%;
  height:60px;
  background-color:#343a40;
}

.top-nav-left{
  float: left;
color: #f8f9fa;
font-size: 1.5rem;
height:60px;
margin-top:15px;
padding-left:10px;
}

.top-nav-right{
  float: right;
color: #c1c1c1;
height:60px;
margin-top:20px;
font-size: 1rem;
padding-left:10px;
padding-right:10px;
}

.top-nav-right a{
  text-decoration:none;
  color:white;
}

.top-nav-right a:visited{
  text-decoration:none;
  color:white;
}

.top-nav-right a:active{
  text-decoration:none;
  color:white;
}

#create_web_button{
  border-radius: 10px;
  border-style: solid;
  padding: 15px;
  background: white;
  color: black;
  text-transform: none;
  padding-top: 20px;
  font-size: 1.5rem;
}

#destroy_button:hover{
  background: #e9ecef;
  }

#destroy_button{
  border-radius: 10px;
  border-style: solid;
  padding: 15px;
  background: white;
  color: black;
  text-transform: none;
  padding-top: 20px;
  font-size: 1.5rem;
  text-decoration:none;
}

#destroy_button a{
  color:black;
  text-decoration:none;
}

#destroy_button a:visited{
  color:black;
  text-decoration:none;
}

#destroy_button a:active{
  color:black;
  text-decoration:none;
}

.table-css{
  background-color:#e9ecef;
  border-color:#212529;
  border-style:solid;
  width:80%;
  font-size:1.5rem;
}
tr:nth-child(even) {
          background-color: #f5f5f5;}
</style>

<!-- Top Nav Bar -->
<div id="top_bar">
  <div class="top-nav-left"> <strong> BlogVault </strong></div>
  <% if current_user %>
    <div class="top-nav-right"> <%= link_to "Home", root_path %> | <b><%= current_user.email %> </b> | <%= link_to "Log Out", destroy_user_session_path, method: :delete %></div>
  <% else %>
    <div class="top-nav-right"> <%= link_to "Home", root_path %> | <%= link_to "Sign Up", new_user_registration_path %> | <%= link_to "Log In", new_user_session_path %></div>
  <%end%>
</div>

<h1>Site Created!</h1>

<center>
<div>
  <table class="table-css">
    <tr>
      <th>Created at</th>
      <td><%= @site.created_at %></td>
    </tr>
    <tr>
      <th>PHP version</th>
      <td><%= @site.php_version %></td>
    </tr>
    <tr>
      <th>Wordpress version</th>
      <td><%= @site.wp_version %></td>
    </tr>
    <tr>
      <th>Site url</th>
      <td><a href = "<%= 'http://206.189.138.203/' + @site.name %>" target="_blank" >http://206.189.138.203/<%= @site.name %></a></td>
    </tr>
    <tr>
      <th>Admin username</th>
      <td><%= @site.admin_username %></td>
    </tr>
    <tr>
      <th>Admin password</th>
      <td><%= @site.admin_password %></td>
    </tr>
    <tr>
      <th>Live till</th>
      <td><%= @site.created_at+6.days %></td>
    </tr>
  </table>
</div>
</center>

<% if current_user and  @site.account_id == current_user.id %>
<br>
<center>
<button id="destroy_button">
  <%= link_to "Delete Site", site_path(@site),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
</button>
</center>
<% end %>